# Generated by Django 4.2.1 on 2023-05-17 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_category_description_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.products'),
        ),
    ]
