# Generated by Django 4.2.1 on 2023-05-18 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_products_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(default=True, max_length=10, validators=[django.core.validators.RegexValidator('^[9,7,8,6]\\d{9}$', 'invalid mobile number')])),
                ('message', models.TextField()),
            ],
        ),
    ]
