# Generated by Django 4.2.1 on 2023-05-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
