# Generated by Django 4.2.1 on 2023-05-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_cart_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Online by card', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.FloatField(default=0),
        ),
    ]
