# Generated by Django 3.0.5 on 2023-06-01 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20230531_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_ref_number',
            field=models.CharField(default='ORD-100000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Online by card', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ReturnMiniOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_requested', models.BooleanField(default=True)),
                ('return_status', models.CharField(choices=[('Processing Return Request', 'Processing Return Request'), ('Item Received by Vendor', 'Item Received by Vendor'), ('Return Denied', 'Return Denied'), ('Return Granted', 'Return Granted')], default='Processing Return Request', max_length=50)),
                ('return_granted', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_reason', models.CharField(blank=True, choices=[('Damaged', 'Damaged'), ('Expired', 'Expired'), ('Ordered Wrong Item', 'Ordered Wrong Item'), ('Received Wrong Item', 'Received Wrong Item'), ('Received Wrong Brand Item', 'Received Wrong Brand Item'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of return.')),
                ('return_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer')),
            ],
            options={
                'ordering': ['return_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('payment_id', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_requested', models.BooleanField(default=True)),
                ('cancel_status', models.CharField(choices=[('Processing Cancel Request', 'Processing Cancel Request'), ('CANCEL Denied', 'CANCEL Denied'), ('Cancel Granted', 'Cancel Granted')], default='Processing Cancel Request', max_length=50)),
                ('cancel_granted', models.BooleanField(default=False)),
                ('cancel_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancel_reason', models.CharField(blank=True, choices=[('Not Needed', 'Not Needed'), ('Ordered Wrong Product', 'Ordered Wrong Product'), ('Receiving To Late', 'Receiving To Late'), ('Select Different Payment Method', 'Select Different Payment Method'), ('Other', 'Other')], max_length=50, null=True)),
                ('review_description', models.TextField(help_text='Please Describe in detail reason of cancel.')),
                ('cancel_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer')),
            ],
            options={
                'ordering': ['-cancel_date'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Payment'),
        ),
    ]
