# Generated by Django 3.0.5 on 2023-06-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_products_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['weight']},
        ),
    ]
